// <auto-generated />
using Apache.Log.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Apache.Log.Data.Migrations
{
    [DbContext(typeof(ApacheLogContext))]
    partial class ApacheLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Apache.Log.Data.Entities.BlacklistedResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullPath");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedResources");

                    b.HasData(
                        new { Id = 1, FullPath = "/phpmyadmin/main.php" },
                        new { Id = 2, FullPath = "/db/main.php" },
                        new { Id = 3, FullPath = "/web/main.php" },
                        new { Id = 4, FullPath = "/PMA/main.php" },
                        new { Id = 5, FullPath = "/dbadmin/main.php" },
                        new { Id = 6, FullPath = "/mysql/main.php" },
                        new { Id = 7, FullPath = "/phpmyadmin2/main.php" },
                        new { Id = 8, FullPath = "/phpmyadmin/read_dump.phpmain.php" },
                        new { Id = 9, FullPath = "/PMA/read_dump.phpmain.php" },
                        new { Id = 10, FullPath = "/mysql/read_dump.phpmain.php" },
                        new { Id = 11, FullPath = "/xampp/phpmyadmin/read_dump.phpmain.php" },
                        new { Id = 12, FullPath = "/typo3/phpmyadmin/read_dump.phpmain.php" },
                        new { Id = 13, FullPath = "/mysqladmin/read_dump.phpmain.php" },
                        new { Id = 14, FullPath = "/admin/read_dump.phpmain.php" },
                        new { Id = 15, FullPath = "/db/read_dump.phpmain.php" }
                    );
                });

            modelBuilder.Entity("Apache.Log.Data.Entities.WhitelistedResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BasePath");

                    b.HasKey("Id");

                    b.HasIndex("BasePath")
                        .IsUnique()
                        .HasFilter("[BasePath] IS NOT NULL");

                    b.ToTable("WhitelistedResources");
                });
#pragma warning restore 612, 618
        }
    }
}
